name: Daily Match Data Update

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch: 

jobs:
  update-matches:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy trueskill tqdm firebase-admin python-dotenv
        
    - name: Export matches from Robot Events API
      env:
        ROBOT_EVENTS_TOKEN: ${{ secrets.ROBOT_EVENTS_TOKEN }}
      run: |
        echo "Starting match export..."
        node export_matches.js
        echo "Match export completed. Checking if matches.csv was created..."
        ls -la matches.csv || echo "matches.csv not found"
      
    - name: Calculate and update TrueSkill ratings
      env:
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
        FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
      run: |
        echo "Starting TrueSkill calculation..."
        python complete_ts2026.py
        echo "TrueSkill calculation completed. Checking if ts2026_ratings.json was created..."
        ls -la ts2026_ratings.json || echo "ts2026_ratings.json not found"
      
    - name: Commit and push updated data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Pull latest changes to avoid conflicts
        git pull origin main --rebase
        
        [ -f matches.csv ] && git add matches.csv
        [ -f ts2026_ratings.json ] && git add ts2026_ratings.json
        
        if ! git diff --staged --quiet; then
          git commit -m "Daily update: matches and TrueSkill ratings $(date)"
          git push
        else
          echo "No changes to commit"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
